line-length = 88
indent-width = 4

target-version = "py312"

[lint]
select = ["BLE", "B", "COM", "D103", "E", "FLY", "F", "I", "PERF", "PLR", "PT", "PLW", "RSE", "SIM", "S", "TD", "UP", "W", "YTT"]
# D202: Newline after doc string (Less readable)
# C416: Unnecessary Comprehension (Slower)
# COM812: Trailing Comma (Only covers single line trailing commas, seems out of place)
# EM: Error messages
# FBT: Boolean Trap (Slower)
# FIX: Fix me
# PLR2004: Magic value used in comparison
# PTH: Use Pathlib (Wants slower API used)
# SIM105: Slower exception suppression (Wants slower check used)
# TD002: Missing author in TODO
# TD003: Missing issue link in TODO
# TRY003: Avoid specifying long messages outside the exception class (Slower and less clear)
ignore = ["D202", "C416", "COM812", "EM", "FBT", "FIX", "PLR2004", "PTH", "SIM105", "TD002", "TD003", "TRY003", "D"]

[lint.extend-per-file-ignores]
# D100: Missing docstring in public module
"setup.py" = ["D100"]
# ANN201: Missing return type
# PT011: Pytest raises
# S101: Assert
"tests/*" = ["ANN201", "PT011", "S101"]

[lint.isort]
known-third-party = ["nuitka"]

[format]
quote-style = "double"
indent-style = "space"
